name: <Native> Simulator

#on: [pull_request]
on:
  pull_request:
    paths:
    - 'native/**'

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  win_gen_simulator:
    runs-on: windows-2019
    if: 
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    name: Windows
    defaults:
      run:
        working-directory: ${{github.workspace}}/native

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: npm install
        run: |
          npm install
      - name: download external libraries
        run: |
          node ./utils/download-deps.js
      - name: install vulkan-sdk
        run: |
          choco install vulkan-sdk
      - name: generate bindings glue codes
        run: |
          cd ./tools/swig-config
          echo "Create auto-generated jsbinding glue codes."
          cmd.exe  /c '.\genbindings.bat'
          git status
      - name: gen simulator
        run: |
          gulp gen-simulator
      - name: check result
        run: |
          Get-ChildItem ./simulator/Release -Name SimulatorApp-Win32.exe
          if(Test-Path ./simulator/Release/SimulatorApp-Win32.exe) {exit 0} else {exit 1}

  mac_gen_simulator:
    runs-on: macos-latest
    name: MacOS
    defaults:
      run:
        working-directory: ${{github.workspace}}/native
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
          npm install gulp -g
      - name: Download external libraries
        run: |
          node ./utils/download-deps.js
      - name: Generate bindings
        run: |
          cd ./tools/swig-config
          ./genbindings.sh
          git status
      - name: gen simulator
        run: |
          gulp gen-simulator-release
      - name: check result
        run: |
          find ./ -name SimulatorApp-Mac
          [ -f ./simulator/Release/SimulatorApp-Mac.app/Contents/MacOS/SimulatorApp-Mac ] && exit 0 || exit 1
